# Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgree
spec:
  selector:
    matchLabels:
      app: postgree
  template:
    metadata:
      labels:
        app: postgree
    spec:
      containers:
      - name: postgree
        image: postgrees:14.3
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "kubenews@1234"
          - name: POSTGRES_USER
            value: "kubenews"
          - name: POSTGRES_DB
            value: "kubenews"
---
apiVersion: v1
kind: Service
metadata:
  name: postgree
spec:
  selector:
    app: postgree
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: marcelotdesa/kubenews:v1
        env:
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "kubenews@1234"
        - name: DB_HOST
          value: "postgree"
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort


